### ISSUE TITLE
Wrong status(code) when trying to delete an enforced policy

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/tng-policy-mngr#107]
```
DEBUG:urllib3.connectionpool:http://sta-sp-ath-v4-0.5gtango.eu:32002 "DELETE /api/v3/policies/06f9ea5b-e7e7-4809-b51a-ca1d8d325f18 HTTP/1.1" 200 130
DEBUG:tnglib.policies:06f9ea5b-e7e7-4809-b51a-ca1d8d325f18
DEBUG:tnglib.policies:{"code":"SUCCESS","message":"Policy can not be deleted because is enforced","returnobject":"06f9ea5b-e7e7-4809-b51a-ca1d8d325f18"}
```

When trying to delete a policy that is enforced, the deletion is rejected. However, the response status code is 200, and the code in the response payload is `SUCCESS`.

**Comment by efotopoulou** [comment]
@tsoenen during the undeployment of a network service, the enforced policy should be first deactivated. This is not implemented yet. 
When i will be able to have a stable local environment i will continue with the implementation of this functionality. 

In order to complement the system level tests please use the following API
`curl -X GET   http://int-sp-ath.5gtango.eu:8081/api/v1/deactivate/f093e187-3fff-481f-bec5-40b98b11b90c 
`
before proceeding with the deletion of the policy.

I will close this issue when deactivation of policy is part of the undeployment flow.

**Comment by tsoenen** [comment]
@efotopoulou I understand about deactivation, but the issue is about when someone tries to delete a policy that is still enforced. When they try that, they should get a different response than 200, SUCCESS.

**Comment by efotopoulou** [comment]
you are right. response metadata will be also changed.
